- .github/workflows/check.yml
- linter_api/src/ast/item.rs
- linter_api/src/ast/item/static_item.rs
- linter_api/src/context.rs
Very descriptive title, I know.
This tries to represent static items with a wrapper type. This should work, however, the documentation page for the `StaticItem` is now split between the wrapper type functions and the specific items. See:
The `ItemBase` documentation is additionally clustered due to the specific type dependent implementation, see:
In general, I like the idea, but the documentation looks worse as a result and is less user-friendly IMO. I'll merge this as a documentation and to test a bit more with it. However, I'll focus my work on a different struct representation.
---
The CI fix just denies warnings and also tests documentation lints in CI
> Try another item representation and fix some CI stuff

- Cargo.lock
- linter_adapter/src/lib.rs
- linter_adapter/src/loader.rs
- linter_api/Cargo.toml
- linter_api/src/ast/common.rs
- linter_api/src/ast/item.rs
- linter_api/src/ast/item/static_item.rs
- linter_api/src/lib.rs
- linter_driver_rustc/Cargo.toml
- linter_driver_rustc/src/ast/common.rs
- linter_driver_rustc/src/ast/item.rs
- linter_lints/src/lib.rs
This PR is related to #6. Basically, I want to remove trait objects from the interface, but also don't copy the same data in each node over and over again. This PR uses a macro to do the common data implementation for each node. Common data for a specific item can now be implemented as follows:
```rs
#[derive(Debug)]
pub struct SomeItem<'ast> {
data: CommonItemData<'ast>,
// Node specific data
}
// This provids access to data stored in 
super::impl_item_data!(StaticItem, Static);
// Now just add functions for node specific data
impl<'ast> SomeItem<'ast> {}
```
I also like how the documentation for the created structs looks. The red border marks the node-specific functions:
This is a huge improvement to the version of #11 IMO
---
This implementation heavily depends on the representation …
> Represent the static item as a struct and represent common data with helper macros

- .cargo/config.toml
I think this makes running the lints a bit simple, while we don't have ui tests (which I want to work on next :))
r? @DevinR528
> Add `linter` as a cargo alias for `linter_lints`

- .github/workflows/rust.yml
- .github/workflows/rust_bors.yml
- bors.toml
- cargo-linter/src/main.rs
- linter_lints/tests/compile_test.rs
This PR renames the existing workflow and adds a new one named `Rust checks (bors)`. The normal `Rust checks` run only uses linux as it's the fastest. I also assume that GH has more linux runners available. The bors run, used for r+ and try calls also run the other platforms.
* Example `Rust checks` run (2:26min): https://github.com/xFrednet/rust-linting/actions/runs/2537277228 
* Example `Rust checks (bors)` run (3:33 min): https://github.com/xFrednet/rust-linting/actions/runs/2537290584
That's it. For now, I'll add myself and @DevinR528 as a reviewer. I'm also fine with r+ own PRs, the usage of bors should mainly ensure that our master is always stable and that we save CI time. A full all OS run takes longer than a single linux run. And that's it, let's see if everything works.
Closes: …
> Add bors-ng and add Windows and Apple CI tests

- .github/workflows/rust_bors.yml
This stops the rerun of the CI steps, since they've been checked by bors on the merge :upside_down_face:
> Remove master rerun since bors check carries over on the commit

- cargo-linter/src/main.rs
- linter_api/src/ast/item.rs
- linter_api/src/ast/ty.rs
- linter_api/src/context.rs
- linter_api/src/lint.rs
- linter_driver_rustc/src/ast/common.rs
- linter_driver_rustc/src/ast/item.rs
- linter_driver_rustc/src/ast/rustc.rs
- linter_driver_rustc/src/ast/ty.rs
- linter_driver_rustc/src/conversion.rs
- linter_lints/src/lib.rs
- linter_lints/tests/ui/find_static.stderr
- linter_lints/tests/ui/find_static.stdout
Enables using `rustc_lint::LateContext` to build warnings/errors for us from our `Lint` and `dyn Span` types.
If you want I can clean up the first few commits, so it's just, fix typos, change `Lint` as one commit, then the unsafe code, and change code in `linter_lints`?
> Use rustc's error reporting mechinery

- cargo-linter/src/main.rs
- linter_adapter/src/lib.rs
- linter_adapter/src/loader.rs
- linter_api/src/ast/item/static_item.rs
- linter_api/src/lib.rs
- linter_driver_rustc/src/ast/item.rs
- linter_driver_rustc/src/ast/rustc.rs
- linter_driver_rustc/src/ast/ty.rs
- linter_driver_rustc/src/conversion.rs
- linter_driver_rustc/src/main.rs
- linter_lints/src/lib.rs
> Use `#![warn(clippy::pedantic)]`

- linter_adapter/README.md
- linter_adapter/src/context.rs
- linter_adapter/src/lib.rs
- linter_api/README.md
- linter_api/src/ast/common.rs
- linter_api/src/ast/common/id.rs
- linter_api/src/ast/common/span.rs
- linter_api/src/ast/item.rs
- linter_api/src/ast/item/use_decl_item.rs
- linter_api/src/context.rs
- linter_api/src/ffi.rs
- linter_api/src/lib.rs
- linter_driver_rustc/src/ast/common.rs
- linter_driver_rustc/src/ast/item.rs
- linter_driver_rustc/src/ast/rustc.rs
- linter_driver_rustc/src/conversion.rs
- linter_driver_rustc/src/main.rs
- linter_lints/src/lib.rs
- linter_lints/tests/ui/find_static.stderr
This PR reworks the *lint-crate/linter_api -> driver* communication to be ABI safe. The previous implementation was using a lot of undefined behavior. An unstable ABI is fun... though I understand why rustc does this.
The basic idea is as follows:
* Driver callbacks are provided as `extern "C"` functions which can safely be called.
* All data send over these calls is FFI safe
* Some conversion magic and FFI safety is done by `linter_api` and `linter_adapter`, which allows drivers to only implement the `DriverContext` trait
---
@HKalbasi This PR was the main blocker for adding a new driver. Once this is merged, you should be able to test ra as another driver. I would highly recommend not looking at the current rustc driver, but implement the ra-driver based on the api/adapter crate and …
> Rework lint-crate -> driver communication 

- cargo-linter/src/main.rs
- linter_adapter/src/context.rs
- linter_api/src/ast/common/id.rs
- linter_api/src/ast/item.rs
- linter_api/src/context.rs
- linter_api/src/ffi.rs
- linter_driver_rustc/src/context.rs
I'm currently working on `Generics` which are tightly bound to types, traits, and items. I believe the next PR will be another monster. Therefore, I'm trying to extract some early commits like these :)
> Add `TyId` and adjust `SymbolID` and `SpanId` visibility

- linter_adapter/src/lib.rs
- linter_api/src/ast/common.rs
- linter_api/src/ast/common/callable.rs
- linter_api/src/ast/generic/bound.rs
- linter_api/src/ast/generic/clause.rs
- linter_api/src/ast/generic/param.rs
- linter_api/src/ast/item.rs
- linter_api/src/ast/item/adt_item.rs
- linter_api/src/ast/item/const_item.rs
- linter_api/src/ast/item/extern_block_item.rs
- linter_api/src/ast/item/fn_item.rs
- linter_api/src/ast/item/impl_item.rs
- linter_api/src/ast/item/mod_item.rs
- linter_api/src/ast/item/trait_item.rs
- linter_api/src/ast/item/ty_alias_item.rs
- linter_api/src/ast/item/use_decl_item.rs
- linter_api/src/ast/mod.rs
- linter_api/src/ast/ty/closure_ty.rs
- linter_api/src/ast/ty/fn_ptr_ty.rs
- linter_api/src/ast/ty/fn_ty.rs
- linter_api/src/ast/ty/impl_trait_ty.rs
- linter_api/src/ast/ty/trait_obj_ty.rs
- linter_api/src/ffi.rs
- linter_api/src/lib.rs
- linter_driver_rustc/src/context/storage.rs
- linter_driver_rustc/src/conversion.rs
- linter_driver_rustc/src/conversion/generic.rs
- linter_driver_rustc/src/conversion/item.rs
- linter_driver_rustc/src/conversion/ty.rs
This was quite fun to write. It's remarkable how a good framework and setup can come together for fast and effective development :3
This closes #49, the driver implementation will be done in as part of #53. This issue also removes almost all traits from our API :tada:. The last trait will be removed with #51 this therefore also closes #6. Also, as usual, some progress on #38.
The normal disclaimer: I'm happy about reviews, but will merge this, if there has been no activity by the time I want to create the next PR. Let's hope this progress keeps up.
---
Closes #49
Closes #6 (The last will be removed as part of #51 )
CC: #53
> Add items and adjust existing ones to the evolving standard

- marker_api/src/ast/common/id.rs
- marker_api/src/ast/mod.rs
- marker_api/src/ast/pat.rs
- marker_api/src/ast/pat/ident_pat.rs
- marker_api/src/ast/pat/or_pat.rs
- marker_api/src/ast/pat/ref_pat.rs
- marker_api/src/ast/pat/rest_pat.rs
- marker_api/src/ast/pat/slice_pat.rs
- marker_api/src/ast/pat/struct_pat.rs
- marker_api/src/ast/pat/tuple_pat.rs
- marker_api/src/ast/pat/wildcard_pat.rs
It's interesting to see how important patterns are to Rust. We use them all the time, often without noticing them. This adds the first few patterns, that can be expressed without expressions. Most of these can't be tested, but I'll try to add the rustc backend for them next.
CC: #50
---
As per usual, I'll merge this, if there has been no outside interaction, by the time I have the next PR ready. And reviews and feedback is very welcome!
> A good chunk of stable patterns for marker

- cargo-marker/src/driver.rs
- cargo-marker/src/main.rs
- marker_driver_rustc/src/conversion/generic.rs
- marker_driver_rustc/src/conversion/item.rs
- marker_driver_rustc/src/conversion/ty.rs
This fixes an ICE for `-> impl Trait` representations. It doesn't work with `-> impl Trait<T>` yet, where `T` is a generic of the item.
I'm not a 100% happy with how the rustc backend is structured, as it feels messy and hard to follow. I'm sadly not sure how to structure it better, as I've never worked on a translation layer like this in rust. My guess is that these things are always a bit messy, but I still hope to find a cleaner solution. For now, I hope that this is good enough.
I also found a small bug with the refactoring from #66 that `cargo dogfood` didn't recompile the driver. It should now do that again :)
r? @Niki4tap
> Fix ICE for `-> impl Trait`

- marker_adapter/src/lib.rs
- marker_api/src/ast/item/adt_item.rs
- marker_api/src/lib.rs
- marker_lints/src/lib.rs
- marker_lints/tests/ui/foo_items.rs
- marker_lints/tests/ui/foo_items.stderr
- `check_fn` for `FnItem`s
- `check_struct` for `StructItem`s
- `check_enum` for `EnumItem`s
- `check_field` for every field def (struct, enum variant)
- `check_variant` for every enum variant def
Also adds implementation for all of them (and `check_const_item`) in `marker_adapter`.
And a test `foo` lint, to ensure they are working :)
> New `check_*` `fn`s

- marker_adapter/src/context.rs
- marker_api/src/ast/common.rs
- marker_api/src/ast/common/id.rs
- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/block_expr.rs
- marker_api/src/ast/expr/bool_lit_expr.rs
- marker_api/src/ast/expr/char_lit_expr.rs
- marker_api/src/ast/expr/float_lit_expr.rs
- marker_api/src/ast/expr/int_lit_expr.rs
- marker_api/src/ast/expr/str_lit_expr.rs
- marker_api/src/ast/expr/unstable_expr.rs
- marker_api/src/ast/generic/param.rs
- marker_api/src/ast/item.rs
- marker_api/src/ast/item/extern_crate_item.rs
- marker_api/src/ast/item/ty_alias_item.rs
- marker_api/src/ast/mod.rs
- marker_api/src/ast/stmt.rs
- marker_api/src/ast/ty.rs
- marker_api/src/ast/ty/alias_ty.rs
- marker_api/src/context.rs
- marker_api/src/interface.rs
- marker_driver_rustc/src/context.rs
This PR adds a basic statement, expression, and body representation to the API. With this, it's possible to represent simple literal expressions and more importantly, use `ExprKind` and `StmtKind` where needed. Merging this allows resolving several TODOs around the API as well as some parallelization.
This PR only includes the API frontend, the rustc backend will be added in a separate PR. As said, I'm not 100% happy with the rustc conversion code and want to focus on that part individually in a separate branch. Sadly, this means that this on its own is not testable. However, I trust rusts type system, and we can always adjust these structs later if needed.
---
cc: https://github.com/rust-marker/marker/issues/52
---
@Niki4tap Would you like to review this? If you don't have the time, I'll …
> Start on expressions and statements, also featuring bodies and some connections between these elements

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- README.md
- cargo-marker/Cargo.toml
- cargo-marker/src/config.rs
- cargo-marker/src/lints.rs
- cargo-marker/src/main.rs
Tracked in #81
Adds initial configuration implementation, checking out one task :)
@xFrednet
> cargo-marker: add initial configuration support

- marker_api/src/ast/pat.rs
- marker_api/src/ast/pat/ref_pat.rs
- marker_api/src/ast/pat/unstable_pat.rs
- marker_driver_rustc/src/conversion/common.rs
- marker_driver_rustc/src/conversion/marker.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/conversion/marker/item.rs
- marker_driver_rustc/src/conversion/marker/pat.rs
This PR adds the \`Unstable\` pattern and a basic rustc backend. Sadly, it's not yet testable, as it first requires bodies and expressions to be implemented. I still wanted to get most of this out of the way while I was still in the context of patterns. Most of this code has been copied from a different dev branch and adjusted to the recent refactorings.
Not too much more to say. I'd prefer to merge this now, but we could wait until expressions and bodies have been implemented to test this first. Though, it might take a while until we reach an expression with refutable patterns.
r? @Niki4tap ^^ So much for me saying that the next PR will take some time to implement :sweat_smile:. As always, feel free to skip it or do the review when you have time :).
Otherwise, to everyone reading this, …
> Add simple rustc backend for patterns

- marker_adapter/src/lib.rs
- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/block_expr.rs
- marker_api/src/ast/expr/str_lit_expr.rs
- marker_api/src/ast/item.rs
- marker_api/src/ast/stmt.rs
- marker_api/src/lib.rs
- marker_driver_rustc/src/conversion/marker/item.rs
While working on the rustc driver, I noticed some missing aspects and utils for statements, expressions, and bodies. The [grammar](https://doc.rust-lang.org/reference/expressions/literal-expr.html) was structured differently than I expected, which made me miss these at first.
I've extracted the API and adapter changes, to keep the PRs smaller overall.
---
Follow-up:  https://github.com/rust-marker/marker/pull/82
CC: https://github.com/rust-marker/marker/issues/52
r? @Niki4tap, would you like to review this? :)
> Adjust `StrLitExpr` node and add util and check methods

- marker_api/src/ast/stmt.rs
- marker_driver_rustc/src/context.rs
- marker_driver_rustc/src/conversion/common.rs
- marker_driver_rustc/src/conversion/marker.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/conversion/marker/expr.rs
- marker_driver_rustc/src/conversion/marker/item.rs
- marker_driver_rustc/src/conversion/marker/stmts.rs
- marker_lints/src/lib.rs
- marker_lints/tests/ui/foo_items.rs
- marker_lints/tests/ui/foo_items.stderr
- marker_lints/tests/ui/print_let_expr.rs
- marker_lints/tests/ui/print_let_expr.stdout
- marker_lints/tests/ui/print_ty.rs
This is the last PR I have queued up right now. It adds the rustc backend and allows us to check the first expressions and statements in lint crates :tada:.
---
This PR feels like the biggest milestone yet, as it adds one of the last conversion modules. Semantic types are the last major `rustc -> marker` module, I can think of. And we could tackle that one after this. For `marker -> rustc` direction, we have diagnostic objects and type checks, like and `implements_trait` method. These should also be unblocked soon. It's cool to see, and maybe a bit frightening, due to all the options.
I'm not sure what I'll work on next, it'll depend on my mood and how much time I have. Though, it'll likely be adding more expressions to the API. And that's enough of story telling ^^
---
r? @Niki4tap If …
> Start on rustc body, expr and stmt conversion

- marker_driver_rustc/src/conversion/common.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/conversion/rustc/common.rs
Pretty much it, just a simple macro to stop repeating the same layout checks for ids again and again.
@xFrednet :)
> Clean up id transmutes in rustc driver

- marker_api/src/ast/common/ast_path.rs
- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/op_exprs.rs
- marker_api/src/ast/generic.rs
- marker_api/src/ffi.rs
- marker_driver_rustc/src/conversion/marker/common.rs
This PR adds a stable representation for most op expressions. The backend will be done in a different PR.
For the operation and precedence names, I was considering if full names like `Addition` would be better than `Add`. However, I think it's better to use the short hand, as most parts of the API do so, as well as rust's [traits](https://doc.rust-lang.org/std/ops/index.html#traits).
Also closes https://github.com/rust-marker/marker/issues/85
---
I took a few days off, and this is me slowly getting back into Marker. Expressions are a bit harder to *express* in a stable way. The next PR might again take a few days, though I hope to get a good rhythm going again.
r? @Niki4tap Would you mind reviewing this if you have time? :)
> Operator Expressions, precedence enum and some minor cleanup

- Cargo.lock
- marker_adapter/Cargo.toml
- marker_adapter/src/context.rs
- marker_adapter/src/loader.rs
Makes `marker_adapter` use `OsString`s to support paths which might not be utf-8.
Fixes #67
> `marker_adapter`: Support non-utf8 paths

- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/ctor_expr.rs
- marker_api/src/ast/expr/pattern_expr.rs
- marker_api/src/ast/item/adt_item.rs
This PR adds an API representation for constructors. The rustc backend will be added in a follow-up PR to keep the changes reviewable.
---
cc: #52
r? @Niki4tap if you don't mind reviewing some more API changes :)
> Add API representation for constructors

- marker_api/src/ast/common/ast_path.rs
- marker_api/src/ast/common/id.rs
- marker_api/src/ast/item/adt_item.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/conversion/marker/expr.rs
- marker_driver_rustc/src/conversion/marker/item.rs
- marker_driver_rustc/src/conversion/marker/pat.rs
- marker_lints/tests/ui/print_ctor.rs
- marker_lints/tests/ui/print_ctor.stdout
Implementing the backend went surprisingly smooth. I really feel like rustc's driver has a good structure now, that supports new additions.
The Ctors being split between `ExprKind::Struct` and `ExprKind::Call` also shows, how marker is more user oriented. I at least feel like marker's representation is way simpler. Though I understand why rustc's representation as well.
---
r? @Niki4tap Would you mind reviewing this? It should hopefully be simple, a lot of these changes (1000+) come from the `print_ctor` test.
cc: #52
follow-up: #110
> Add rustc backend for Ctors

- marker_adapter/src/context.rs
- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/block_expr.rs
- marker_api/src/ast/expr/call_exprs.rs
- marker_api/src/context.rs
- marker_driver_rustc/src/context.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/conversion/marker/expr.rs
- marker_lints/tests/ui/print_let_expr.rs
- marker_lints/tests/ui/print_let_expr.stdout
- marker_lints/tests/ui/print_object_exprs.rs
- marker_lints/tests/ui/print_object_exprs.stdout
This PR adds the `ExprKind::Method` variant and supports the representation of unsafe blocks.
---
r? @Niki4tap My understanding is, that you're fine with me pinging you for PRs. If you have the time, I'd value your feedback. :)
cc: #52
> Add `MethodExpr` and rustc backend

- marker_driver_rustc/src/context.rs
- marker_driver_rustc/src/context/storage.rs
- marker_driver_rustc/src/conversion/marker.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/conversion/marker/expr.rs
- marker_driver_rustc/src/conversion/marker/generics.rs
- marker_driver_rustc/src/conversion/marker/item.rs
- marker_driver_rustc/src/conversion/marker/pat.rs
- marker_driver_rustc/src/conversion/marker/stmts.rs
- marker_driver_rustc/src/conversion/marker/ty.rs
- marker_driver_rustc/src/conversion/rustc.rs
- marker_driver_rustc/src/conversion/rustc/common.rs
- marker_driver_rustc/src/conversion/rustc/unstable.rs
This PR refactors the signature of the `alloc()` function to take the object instead of a closure and adds a wrapper for `MarkerConverterInner` (previously `MarkerConversionContext`)
---
95% of the changes are superficial. I think it's best if I `r=me`. Functional changes on this base will be done in follow-up PRs :)
> Refactorings and resulting format changes in rustc's driver

- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/cond_expr.rs
- marker_api/src/ast/stmt.rs
- marker_driver_rustc/src/conversion/marker/expr.rs
- marker_lints/src/lib.rs
- marker_lints/tests/ui/print_cond_expr.rs
- marker_lints/tests/ui/print_cond_expr.stdout
This adds API representations for `if`, `if let` and `match` expressions, getting us one step closer.
As always, most of the changes are just UI test output.
---
cc: #52
r? @Niki4tap Would you mind taking a look at this? :)
> `if`, `if let` and `match` representations

- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/op_exprs.rs
- marker_api/src/ast/pat.rs
- marker_driver_rustc/src/conversion/marker/expr.rs
- marker_driver_rustc/src/conversion/marker/pat.rs
- marker_driver_rustc/src/conversion/marker/stmts.rs
- marker_driver_rustc/src/main.rs
- marker_lints/tests/ui/print_assign_expr.rs
- marker_lints/tests/ui/print_assign_expr.stdout
This PR adds the assign expression to the API. The implementation was a bit complicated design wise, I created https://github.com/rust-marker/design/issues/35 to discuss other solutions and review this representation before v1.0.0.
Before reviewing this, I suggest checking this [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0da87ed83a1f80c61b026f54bf75d077) with *Show HIR* to see how rustc desugars some assign expressions. `#[clippy::dump]` and then *Tools > Clippy* can also always be helpful.
I also appreciate feedback on the design.
---
r? @Niki4tap Would you mind giving this a review? We can also wait a few days to see if we get any feedback on the design issue. On the other hand, we can always revert these changes :). Besides that, I'm trying to …
> Add AssignExpr API represention

- .github/workflows/rust.yml
- .github/workflows/rust_bors.yml
- cargo-marker/src/driver.rs
- marker_adapter/src/loader.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/conversion/marker/expr.rs
- marker_driver_rustc/src/conversion/marker/generics.rs
- marker_driver_rustc/src/conversion/marker/item.rs
- marker_driver_rustc/src/conversion/marker/ty.rs
- marker_driver_rustc/src/main.rs
- rust-toolchain
- util/update-toolchain.sh
> bump nightly -> 2023-01-26

- marker_adapter/src/context.rs
- marker_api/src/ast/common.rs
- marker_api/src/ast/common/id.rs
- marker_api/src/ast/common/span.rs
- marker_api/src/ast/item.rs
- marker_api/src/ast/item/adt_item.rs
- marker_api/src/ast/stmt.rs
- marker_api/src/context.rs
- marker_api/src/diagnostic.rs
- marker_api/src/ffi.rs
- marker_api/src/lib.rs
- marker_api/src/lint.rs
- marker_driver_rustc/src/context.rs
- marker_driver_rustc/src/conversion/common.rs
- marker_driver_rustc/src/conversion/marker.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/conversion/marker/item.rs
- marker_driver_rustc/src/conversion/marker/stmts.rs
- marker_driver_rustc/src/conversion/rustc.rs
- marker_driver_rustc/src/conversion/rustc/common.rs
- marker_driver_rustc/src/conversion/rustc/unstable.rs
- marker_lints/src/lib.rs
- marker_lints/tests/ui/find_item.stderr
- marker_lints/tests/ui/foo_items.stderr
This PR adds a new `DiagnosticBuilder` to the API to create beautiful diagnostics with help and note messages. This will also allow us to include the expression span, in the print tests. Generally, I'm pretty happy with the concept :)
---
Adding new context callbacks to the API currently requires a lot of boilerplate code. I doubt that we can avoid that right now, but I'll try to look at options to generate a part of it. That would at least help with the implementation and review part.
---
r? @Niki4tap Sorry for requesting this review direction after the last one. You are welcome to take your time or pass the review if you don't have time. It's also totally fine, if you just review the API and doc changes. The backend is mostly verified by the tests :)
Closes #47
Closes #92 (This PR adds …
> Emit lints using a diagnostic builder

- .github/workflows/rust.yml
- .github/workflows/rust_bors.yml
- cargo-marker/src/driver.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/main.rs
- rust-toolchain
- util/update-toolchain.sh
Closes: https://github.com/rust-marker/marker/issues/123
r? @ghost
> bump nightly -> 2023-04-20

- Cargo.lock
- cargo-marker/Cargo.toml
- cargo-marker/src/config.rs
- cargo-marker/src/lints.rs
- cargo-marker/src/main.rs
Its been a while since I've worked on this, but I've finally took the time to finish it.
This PR adds git support to marker so this now works:
```toml
[workspace.metadata.marker.lints]
marker_lints = { git = "https://github.com/rust-marker/marker" }
```
It makes use of [`cargo_fetch`](https://github.com/Niki4tap/cargo_fetch) library which I made for this specific use-case, which is essentially just a thin wrapper around `cargo` library (so the builds are now way slower :p).
I'll try to maintain the library to my best capacity, and prioritize marker's goals whenever needed.
Addition of the library also technically allows for any kind of package to be downloaded, so this also *technically* supports registries, though this PR does not implement it, because this is blocked on marker APIs …
> cargo-marker: add git support

- marker_api/src/ast/common/ast_path.rs
- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/block_expr.rs
- marker_driver_rustc/src/conversion/marker.rs
- marker_driver_rustc/src/conversion/marker/common.rs
- marker_driver_rustc/src/conversion/marker/expr.rs
- marker_lints/tests/ui/print_closure_expr.rs
- marker_lints/tests/ui/print_closure_expr.stderr
- marker_lints/tests/ui/print_cond_expr.rs
- marker_lints/tests/ui/print_cond_expr.stderr
- marker_lints/tests/ui/print_op.rs
- marker_lints/tests/ui/print_op.stderr
- marker_lints/tests/ui/print_ty.rs
- marker_lints/tests/ui/print_ty.stderr
This PR fixes all the nits and adds all the expressions needed to make `cargo dogfood` pass. This almost finishes the work from #52, besides the `.await` expression.
There is not too much more to say. I thought about adding `cargo dogfood` to the CI, but I think it's better to wait with that, until we have the first custom lints. For now, this is a nice step into the right direction.
---
cc: https://github.com/rust-marker/marker/issues/52
> Dogfood finally passes :tada: 

- marker_adapter/src/context.rs
- marker_api/src/context.rs
- marker_driver_rustc/src/context.rs
- marker_driver_rustc/src/context/storage.rs
- marker_driver_rustc/src/conversion/marker.rs
- marker_lints/src/lib.rs
- marker_lints/tests/ui/item_id_resolution.rs
- marker_lints/tests/ui/item_id_resolution.stderr
This is not the ideal implementation, as it requires manual path resolution. Rustc sadly hides the related functions from the public interface. https://github.com/rust-marker/marker/issues/93 provides additional information.
Closes: https://github.com/rust-marker/marker/issues/93
> API: Add interface to resolve `TyDefId` by a path string

- README.md
- cargo-marker/Cargo.toml
- cargo-marker/README.md
- cargo-marker/src/main.rs
- util/update-toolchain.sh
This PR adds a `README.md` file to the `cargo_marker` crate. The *Installation* section is purely theoretical, right now, as the crate has not yet been published to crates.io. But the name is reserved and it should work exactly like that, once everything is up in running.
Probably not much more to say. Any reviews are welcome and highly appreciated :)
---
cc: https://github.com/rust-marker/marker/issues/151
> Cargo: Add `README` to `cargo_marker`

- cargo-marker/src/config.rs
- marker_adapter/src/lib.rs
- marker_adapter/src/loader.rs
- marker_api/Cargo.toml
- marker_api/README.md
- marker_api/src/context.rs
- marker_api/src/diagnostic.rs
- marker_api/src/ffi.rs
- marker_api/src/interface.rs
- marker_api/src/lib.rs
- marker_api/src/lint.rs
- marker_uitest/src/lib.rs
- marker_uitest/tests/ui/foo_items.rs
- marker_uitest/tests/ui/foo_items.stderr
- marker_uitest/tests/ui/print_ty.stderr
The motivation behind this change is explained in https://github.com/rust-marker/marker/issues/147. The `lint_pass_fns` macro is basically removed in favor of manually writing some boilerplate. This PR is also a preparation for following PRs.
The last commit also addresses https://github.com/rust-marker/marker/issues/146.
---
Closes https://github.com/rust-marker/marker/issues/147 
Closes https://github.com/rust-marker/marker/issues/146
Any reviews are welcome :)
> Refactoring: Migrating away from `lint_pass_fns` macro code gen

- .github/workflows/rust.yml
- .github/workflows/rust_bors.yml
- Cargo.lock
- Cargo.toml
- marker_adapter/Cargo.toml
- marker_adapter/src/lib.rs
- marker_api/src/ast/expr/block_expr.rs
- marker_api/src/ast/expr/control_flow_expr.rs
- marker_api/src/ast/expr/ctor_expr.rs
- marker_api/src/ast/item/fn_item.rs
- marker_api/src/ast/pat/struct_pat.rs
- marker_rustc_driver/src/conversion/marker.rs
- marker_rustc_driver/src/conversion/marker/common.rs
- marker_rustc_driver/src/conversion/marker/expr.rs
- marker_rustc_driver/src/conversion/marker/pat.rs
- marker_rustc_driver/src/conversion/marker/ty.rs
- marker_uitest/src/lib.rs
- marker_uitest/tests/ui/item_id_resolution.rs
- marker_uitest/tests/ui/print_assign_expr.stderr
- marker_uitest/tests/ui/print_cond_expr.stderr
- marker_uitest/tests/ui/print_loop_expr.stderr
- marker_uitest/tests/ui/print_semantic_ty.rs
- marker_uitest/tests/ui/print_semantic_ty.stderr
- marker_utils/Cargo.toml
- marker_utils/README.md
- marker_utils/src/lib.rs
- marker_utils/src/visitor.rs
This PR is an important milestone. It adds the new `marker_utils` crate with a new `Visitor` trait. This trait is then directly used to traverse the entire AST in the `marker_adapter` crate. And finally, dogfood, or better say a clean dogfood. It just passes, able to translate everything. I don't quite know how to feel about this, tbh.
The number of changes sadly exploded, sorry if someone actually looks at this :sweat_smile:
---
cc: https://github.com/rust-marker/marker/issues/159 I think the design still needs some small adjustments, like being able to limit the scope of what is being visited etc.
> Utils: Setup `marker_utils` project and add a `Visitor` (First clean dogfood)

- marker_rustc_driver/src/context.rs
- marker_rustc_driver/src/conversion/marker/common.rs
- marker_rustc_driver/src/conversion/rustc/common.rs
- marker_rustc_driver/src/conversion/rustc/unstable.rs
- marker_rustc_driver/src/main.rs
Closes https://github.com/rust-marker/marker/issues/25
> Rustc: Enable `non_exhaustive_omitted_patterns_lint` feature and lint

- .github/workflows/rust.yml
- .github/workflows/rust_bors.yml
- cargo-marker/README.md
- cargo-marker/src/backend/driver.rs
- marker_api/src/context.rs
- marker_rustc_driver/src/main.rs
- rust-toolchain
- util/update-toolchain.sh
Luckly a simple bump :D
---
Closes: https://github.com/rust-marker/marker/issues/134
> Bump nightly -> 2023-07-13

- marker_api/README.md
- marker_api/src/context.rs
- marker_api/src/lib.rs
- marker_api/src/prelude.rs
This PR basically rewrites the entire readme of the `marker_api` crate. It also adds the `marker_api::prelude` module for convenience. What a beautiful PR :D
[:framed_picture: Rendered `README.md` :framed_picture:](https://github.com/xFrednet/marker/blob/151-who-reads-api-docs-anyways/marker_api/README.md)
---
cc: https://github.com/rust-marker/marker/issues/151
> API: The README of marker_api rebirth and a new `marker_api::prelude` module

- marker_adapter/src/context.rs
- marker_api/src/ast/common/id.rs
- marker_api/src/ast/common/span.rs
- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/op_exprs.rs
- marker_api/src/context.rs
- marker_api/src/ffi.rs
- marker_api/src/lint.rs
- marker_rustc_driver/src/context.rs
- marker_rustc_driver/src/context/storage.rs
- marker_rustc_driver/src/conversion/marker.rs
- marker_rustc_driver/src/conversion/marker/common.rs
- marker_rustc_driver/src/conversion/marker/generics.rs
- marker_rustc_driver/src/conversion/marker/item.rs
- marker_rustc_driver/src/conversion/marker/pat.rs
- marker_rustc_driver/src/conversion/marker/ty.rs
- marker_rustc_driver/src/conversion/rustc/common.rs
- marker_rustc_driver/src/conversion/rustc/unstable.rs
- marker_uilints/src/lib.rs
- marker_uilints/tests/ui/find_item.rs
- marker_uilints/tests/ui/find_item.stderr
- marker_uilints/tests/ui/print_cond_expr.rs
- marker_uilints/tests/ui/print_cond_expr.stderr
- marker_uilints/tests/ui/print_span.rs
- marker_uilints/tests/ui/print_span.stderr
- marker_uilints/tests/ui/test-lang-items.rs
- marker_uilints/tests/ui/test_no_async_ice.rs
- marker_uilints/tests/ui/test_no_async_ice.stderr
I ran Marker on several crates and fixed ICEs as they came up. I also found a soundness issue in the previous `SpanSource` implementation. Totally fixing spans is a task for another darker day, but this should work well enough for v0.1.0.
I tested Marker on the following crates:
* `clap`
* `parking_lot`
* `rand`
* `regex`
* `serde`
* `time`
* `tokio`
* `unicode-xid`
I want to test more crates, also as part of the CI, but this PR has grown too much already.
> Rustc: Fix spans, sound and ICEs

- .cargo/config.toml
- .github/workflows/rust.yml
- .github/workflows/rust_bors.yml
- Cargo.toml
- bors.toml
- cargo-marker/Cargo.toml
- marker_adapter/Cargo.toml
- marker_adapter/src/loader.rs
- marker_api/Cargo.toml
- marker_api/src/lint.rs
- marker_lints/Cargo.toml
- marker_rustc_driver/Cargo.toml
- marker_uilints/Cargo.toml
- marker_uilints/src/lib.rs
- marker_uitest/Cargo.toml
- marker_utils/Cargo.toml
- rustfmt.toml
- scripts/download/cargo-machete.sh
- scripts/download/lib.sh
- scripts/download/taplo.sh
- scripts/download/typos.sh
- scripts/lib.sh
- taplo.toml
Some of this code was taken from [my public repo](https://github.com/Veetaha/snowpity/blob/master/.github/workflows/ci.yml), and some of the scripts were copied from my private repo (with the permission to do so gained as well).
- [`typos`](https://github.com/crate-ci/typos): this one has a static dictionary of known typos, and is famous for very low rate of false positives for that reason. It analyzes all text files in the repo and finds known typos in them. It's possible to autofix all typos with `typos -w`. 
- [`taplo`](https://github.com/tamasfe/taplo): formatter for TOML files just like `rustfmt`, it's possible to auto-format toml files with `taplo fmt` and configure the style as you wish in `taplo.toml`. 
- [`cargo-machete`](https://github.com/bnjbvr/cargo-machete) a heuristic check …
> Add several more checks to CI

- marker_api/src/ast/common/callable.rs
- marker_api/src/ast/item/fn_item.rs
- marker_rustc_driver/src/conversion/marker.rs
- marker_rustc_driver/src/conversion/marker/expr.rs
- marker_rustc_driver/src/conversion/marker/item.rs
- marker_uilints/src/lib.rs
- marker_uilints/tests/ui/item/print_fn_item.rs
- marker_uilints/tests/ui/item/print_fn_item.stderr
- marker_uilints/tests/ui/print_adt_item.stderr
- marker_uilints/tests/ui/print_const_generics.stderr
- marker_uilints/tests/uitest.rs
> API: Remove `CallableData` from `FnItem` and use fields instead

- cargo-marker/src/backend/lints/fetch.rs
- cargo-marker/src/backend/toolchain.rs
Closes #188
Tested using rust-toolchain 1.65.0
> cargo: Pass the toolchain to all instances of MetadataCommand

- marker_adapter/src/context.rs
- marker_api/src/ast/common/span.rs
- marker_api/src/ast/item.rs
- marker_api/src/context.rs
- marker_rustc_driver/src/context.rs
- marker_rustc_driver/src/conversion/marker/item.rs
- marker_uilints/tests/ui/item/print_fn_item.stderr
- marker_uilints/tests/ui/print_adt_item.stderr
- marker_uilints/tests/ui/print_const_generics.stderr
This fixes a panic for trait items without a body.
Closes: rust-marker/marker#192
> API: Always request `Span`s by id (Remove `SpanOwner` enum)

- CONTRIBUTING.md
- README.md
- cargo-marker/README.md
- marker_adapter/README.md
- marker_api/README.md
- marker_lints/README.md
- marker_rustc_driver/README.md
- marker_uilints/README.md
- marker_uitest/README.md
- marker_utils/README.md
I finally got around to writing a `CONTRIBUTING.md` :tada:
This should also rust-marker/marker#59, as Marker now has documentation on how to install it from `crates.io` and how to get started with development. Documentation can always be improved, but this is a solid start for now :)
[:framed_picture: Rendered :framed_picture:](https://github.com/xFrednet/marker/blob/059-contribute-to-contributing/CONTRIBUTING.md)
---
Closes rust-marker/marker#59
> Doc: Add `CONTRIBUTING.md`

- marker_adapter/src/lib.rs
- marker_api/src/interface.rs
- marker_lints/src/lib.rs
- marker_rustc_driver/src/conversion/rustc.rs
- marker_rustc_driver/src/conversion/rustc/common.rs
- marker_rustc_driver/src/conversion/rustc/unstable.rs
- marker_rustc_driver/src/lint_pass.rs
- marker_rustc_driver/src/main.rs
- marker_uilints/tests/ui/lint_level_attributes.rs
- marker_uilints/tests/ui/lint_level_attributes.stderr
Registering the lints early, makes rustc track the lint level correctly (Assuming that marker is registered as a tool)
Not much more to say, I wrote this thing last night and I was super tired at the end. But it works, that's the important part ^^
---
Closes: rust-marker/marker#200
> Rustc: Create `Adapter` early to register lints with rustc

- Cargo.lock
- marker_adapter/Cargo.toml
- marker_adapter/src/lib.rs
- marker_adapter/src/loader.rs
- marker_rustc_driver/src/lint_pass.rs
- marker_rustc_driver/src/main.rs
This was a fight, it required some refactoring in `marker_adapter` to get the information, which lint crates should actually be tracked.
The process of invoking the compiler programmatically is also confusing, IMO. I don't know how anyone should be able to figure this out, without the existence of Clippy as a reference. Even with the reference and my tries to leave helpful comments, it took some time to get back into it.
If anyone is interested in reviewing this, I suggest just taking a look at the `register_tracked_files` function and the `marker_adapter` changes. The rest is first class spaghetti code which will hopefully work flawlessly:tm:
---
Testing this is also... a challenge, in the end I had to manually install the driver, open a different project and add a path lint crate. Then …
> Rustc: Avoid caching by tracking lint crates and env vars

- .github/workflows/gh-pages.yml
In rust-marker/marker#212 I broke the book, by using too much copy-pasta, this should fix the issue quickly.
Sorry :sweat_smile:
> CI: Fix Marker Book deployment

- .cargo/config.toml
- Cargo.lock
- cargo-marker/Cargo.toml
- cargo-marker/src/backend/driver.rs
- cargo-marker/src/backend/toolchain.rs
- cargo-marker/src/cli.rs
- cargo-marker/src/main.rs
- marker_uitest/src/lib.rs
Just a simple refactoring. At first, I was a bit hesitant, but I believe that this is the better way to handle Marker's CLI. Only the `--test-setup` argument changed into a hidden subcommand, the rest should be the same as before.
Nothing more to say otherwise. Reviews are appreciated. For everyone reading this, have a beautiful day! :D
> Cargo: Build CLAP command using derive

- Cargo.lock
- cargo-marker/Cargo.toml
- cargo-marker/src/backend.rs
- cargo-marker/src/backend/cargo.rs
- cargo-marker/src/backend/driver.rs
- cargo-marker/src/backend/lints/fetch.rs
- cargo-marker/src/backend/toolchain.rs
- cargo-marker/src/cli.rs
- cargo-marker/src/config.rs
- cargo-marker/src/exit.rs
- cargo-marker/src/main.rs
- cargo-marker/src/utils.rs
- marker_adapter/src/loader.rs
- marker_rustc_driver/src/context.rs
After resolving this issue https://github.com/rust-marker/marker/issues/188, this problem was revealed.
I didn't create an issue, I just fixed it in this PR.
When `cargo` of the new version tries to call `rustc` of the old version and pass it arguments that it does not support, the program breaks.
This happens when executing a command in `cargo_metadata_command()`.
Description of the situation in the diagram:
Inside `MetadataCommand::new()` creates `cargo metadata` which calls `rustc`.
It, in turn, takes the toolchain from `PATH="~/.rustup/toolchains/1.65.0-*"`
Also in repository with 1.65.0 in rust-toolchain file the following error occurs:
```
$ cargo marker
Compiling Lints:
error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See …
```
> Fixed toolchain version drift, improved error handling, config loading and refactoring.

- Cargo.lock
- Cargo.toml
- cargo-marker/Cargo.toml
- cargo-marker/src/backend/driver.rs
- marker_adapter/Cargo.toml
- marker_api/Cargo.toml
- marker_lints/Cargo.toml
- marker_rustc_driver/Cargo.toml
- marker_uilints/Cargo.toml
- marker_uitest/Cargo.toml
- marker_utils/Cargo.toml
I hope this is the correct usage of `workspace` information. I've bumped the version in the manifest, but left the version in the documentation as `0.1.1`, since I believe that new comers will first look at the repository and should therefore see the last released version and not the name of the new one. I'll maybe write a script at some point, to automatically update all versions. Declaring the version on the workspace level is already a major improvement :)
---
Closes: rust-marker/marker#226
> Chore: Use `workspace.package` and `workspace.dependencies` and bump version to `v0.2.0-dev`

- cargo-marker/README.md
- cargo-marker/src/backend/driver.rs
- marker_rustc_driver/README.md
- marker_rustc_driver/src/context.rs
- marker_rustc_driver/src/conversion/marker/common.rs
- marker_rustc_driver/src/conversion/marker/expr.rs
- marker_rustc_driver/src/conversion/marker/generics.rs
- marker_rustc_driver/src/conversion/marker/item.rs
- marker_rustc_driver/src/conversion/marker/pat.rs
- marker_rustc_driver/src/conversion/marker/ty.rs
- marker_rustc_driver/src/main.rs
- marker_uilints/tests/ui/lint_ice_message.stderr
- marker_uilints/tests/ui/rustc_ice_message.stderr
- rust-toolchain.toml
- util/update-toolchain.sh
Another showcase, why we need something like Marker. This PR migrates every lint crate that uses marker's public API to use `nightly-2024-08-24` :)
Closes: https://github.com/rust-marker/marker/issues/219
> Bump nightly -> 2023-08-24

- Cargo.lock
- Cargo.toml
- cargo-marker/Cargo.toml
- cargo-marker/src/backend.rs
- cargo-marker/src/backend/driver.rs
- cargo-marker/src/backend/lints.rs
- cargo-marker/src/backend/lints/build.rs
- cargo-marker/src/backend/lints/fetch.rs
- cargo-marker/src/backend/toolchain.rs
- cargo-marker/src/observability/display/cli.rs
- cargo-marker/src/utils.rs
- cargo-marker/src/utils/utf8.rs
- marker_adapter/Cargo.toml
- marker_adapter/src/loader.rs
- marker_rustc_driver/Cargo.toml
- marker_rustc_driver/src/main.rs
Trait supports conversion `Vec<u8> -> String` and `PathBuf -> Utf8PathBuf`. 
Changing the path type to `Utf8Path` and `Utf8PathBuf` ensures that they have only UTF-8 encoding.
And also, they implement `Display`, which is also very convenient :)
> Type constraint for paths and IntoUtf8 trait

- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/op_exprs.rs
- marker_rustc_driver/src/conversion/marker/expr.rs
- marker_uilints/tests/ui/print_cond_expr.stderr
- marker_utils/src/visitor.rs
The `?` operator is officially called the *ErrorPropagationExpression* in [Rust's grammar](https://doc.rust-lang.org/reference/expressions/operator-expr.html#the-question-mark-operator). However, I've rarely seen people actually call it by that name. Even the documentation doesn't call it that after the grammar definition.
Before, I've called it the *QuestionMarkOperator*, but this name feels a bit off, as that describes how it's written, but not what it does. I have the impression, that the community commonly calls this operator the *Try* operator. That's at least the name I would use and what I've seen in a few blog posts.
This change is open for discussion. If you have any thoughts, please share them! :)
> API: Rename `QuestionMarkExpr` -> `TryExpr` (Breaking change)

- cargo-marker/src/backend.rs
- cargo-marker/src/backend/lints/fetch.rs
- cargo-marker/src/cli.rs
- cargo-marker/src/cli/check.rs
- cargo-marker/src/cli/setup.rs
- cargo-marker/src/cli/test_setup.rs
- cargo-marker/src/config.rs
- cargo-marker/src/main.rs
Every CLI command now lives in a separate module. This helps with readability because code is now categorized via module files. Previously it was hard to read it because everything was in one file.
Replaced some leftover `OsString` handling with just `String`.
Replaced `HashMap` with `BTreeMap` in several places to have stable sorting. Meaning, for example, if you run `cargo marker` several times lint crates will be compiled in the same order (instead of a random one). See also this [doc](https://elastio.notion.site/Prefer-BTreeMap-Set-6042af3bc69041348c07170722b45bd1?pvs=4) for additional reasoning.
Changed some `pub` types to `pub(crate)` since this is a binary crate nothing should actually be `pub` here.
> Reorganize the CLI to a consistent module structure 

- scripts/release/install.ps1
- scripts/release/install.sh
- scripts/release/set-version.sh
- scripts/release/snapshot.diff
- scripts/update-toolchain.sh
ChatGPT rules.However of course it made a ton of mistakes converting bash to powershell, and I of course I had to stare at powershell syntax with their poor error messages for some time. But, anyway, it's past that and the script works.
You can test it using a separate branch where I configured it to work with my fork.
```ps1
curl.exe --location --silent --fail --show-error --retry 5 --retry-connrefused `
https://raw.githubusercontent.com/Veetaha/marker/feat/install-on-windows-test/scripts/release/install.ps1 | powershell -command -
```
This was inspired by the installation script in [deno](https://github.com/denoland/deno). Turns out both `curl.exe` and `tar.exe` are [available on windows by default](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-an …
> Add windows installation script

- marker_adapter/src/context.rs
- marker_api/src/ast/common/id.rs
- marker_api/src/ast/common/span.rs
- marker_api/src/ast/expr.rs
- marker_api/src/ast/expr/lit_expr.rs
- marker_api/src/ast/item.rs
- marker_api/src/ast/item/adt_item.rs
- marker_api/src/ast/stmt.rs
- marker_api/src/context.rs
- marker_api/src/diagnostic.rs
- marker_api/src/lib.rs
- marker_api/src/prelude.rs
- marker_lints/src/lib.rs
- marker_lints/tests/ui/diag_msg_uppercase_start.rs
- marker_lints/tests/ui/diag_msg_uppercase_start.stderr
- marker_rustc_driver/src/context.rs
- marker_rustc_driver/src/conversion/rustc/common.rs
- marker_uilints/src/lib.rs
- marker_uilints/src/utils.rs
This came up in the discussion of rust-marker/marker#189. I believe the previous design was the correct technical implementation, I agree that it's quite verbose and potentially confusing to new users. Now we have a bunch of documentation, how `AstContext::emit_lint` should be used, and it only takes three parameters for a minimal lint emission. :tada: 
@Veetaha would you mind providing feedback on this PR? Since this came up in the discussion from rust-marker/marker#189
> API: Reduce parameters for `AstContext::emit_lint` and add docs

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- marker_lints/tests/uitest.rs
- marker_uilints/tests/ui/expr/sugar/for_loop.stderr
- marker_uilints/tests/ui/expr/sugar/while_loop.stderr
- marker_uilints/tests/ui/print_let_expr.stderr
- marker_uilints/tests/uitest.rs
- marker_uitest/Cargo.toml
- marker_uitest/src/lib.rs
Not much to say. I just checked crates.io and updated every dependency I could. Then I ran `cargo update` and everything was done.
Updating `ui_test` was a bin painful due to the big version difference, but it seems to be working now :D
> uitest: Update `ui_test` from `v0.11.7` to `v0.21.2` and other deps

- .github/workflows/ci.yml
- marker_api/src/ast/ty/fn_ty.rs
- scripts/download/cargo-semver-checks.sh
This PR adds [cargo-semver-checks](https://github.com/obi1kenobi/cargo-semver-checks) to marker's CI, as a sanity check. This CI job shouldn't block a PR from being merged, but it's a good indicator, that a change should be listed in Marker's changelog.
Ideally, I would have liked a job status, between success and failed. Maybe a nice orange icon, saying that the job failed, but that that's acceptable? I know GitLab had something like this in the past, but GitHub doesn't seem to support it. It's either: success, failure, or cancelled. Oh well, an indicator is an indicator.
Here is an example, of a failed semver check, due to a removed public function: https://github.com/xFrednet/marker/actions/runs/6340462879/job/17221897343?pr=1
---
I should really stop procrastinating on my uni …
> CI: Add semantic versioning test for controlled breakage

- .github/workflows/ci.yml
- .github/workflows/release-on-tag.yml
- .github/workflows/release.yml
- CHANGELOG.md
- action.yml
- docs/internal/release.md
- scripts/release/get-git-tags.sh
- scripts/release/install.ps1
- scripts/release/install.sh
Added a github action template that will allow anyone to include `marker` into their CI using the following code:
```yaml
- uses: rust-marker/marker@v0.3
```
This PR encompasses several important changes.
This is a dead simple composite github action template file that just runs a couple of bash lines. It is cross-platform, meaning the same syntax may be used for both `windows` and `unix`. The action handles the selection of the bash or powershell script internally.
It runs `cargo marker` command by default. That can be disabled with `install-only` option if there is some more elaborate use case than this. The action is pretty conservative in its API, as it exposes just this single input parameter for now. I believe in the future its API may grow. For example, it we may have `lints` input …
> Add a github action

- marker_api/src/ast/ty/fn_ty.rs
I broke the API for testing in rust-marker/marker#262, but forgot to undo the change before merging. This just corrects the mistake.
> API: Undo accidental API break from rust-marker/marker#262

- CHANGELOG.md
- marker_adapter/src/context.rs
- marker_adapter/src/context/map.rs
- marker_api/src/context.rs
- marker_api/src/context/map.rs
- marker_api/src/lint.rs
- marker_api/src/prelude.rs
- marker_rustc_driver/src/context.rs
- marker_rustc_driver/src/context/map.rs
- marker_rustc_driver/src/conversion/marker.rs
- marker_rustc_driver/src/conversion/marker/item.rs
- marker_uilints/src/lib.rs
- marker_uilints/src/utils.rs
- marker_uilints/tests/ui/context/test_ast_map.rs
- marker_uilints/tests/ui/context/test_ast_map.stderr
- marker_uilints/tests/uitest.rs
- marker_utils/src/visitor.rs
This PR cleans up a central part of Marker, the callbacks to the driver. With the old `AstContext` continuously growing, I had the feeling that it was getting more and more overwhelming to work with. It only had a few public functions, but they had a whole range of functions. The old `AstContext` was basically a box that every tool was thrown into, without much consideration. It was like storing the stone drill next to the sewing kit and toaster. Definitely possible, but probably not useful.
A previous PR already renamed `AstContext` to `MarkerContext` for reasons described in rust-marker/marker#243.
This PR tried to add new structure to the while `context` module. From now on, we'll try to group similar functions together. Some general functions, like `emit_lint` will be available …
> API: Add `AstMap` (`MarkerContext` cleanup and more breakage :bomb:)

- CHANGELOG.md
This PR sets the version number in the changelog, according to Marker's release docs and updates the release description.
This should be the last PR merged, before the release. I'll probably need to rebase after rust-marker/marker#268 and rust-marker/marker#255 have been merged, but that should be fairly simple.
> Doc: Update changelog for `v0.3.0`

- marker_uitest/src/lib.rs
Closes: rust-marker/marker#276
> uitest: Normalize path separators for `$DIR` replacement

- .github/workflows/release-on-tag.yml
- CONTRIBUTING.md
- Cargo.toml
- README.md
- cargo-marker/README.md
- cargo-marker/src/backend/driver.rs
- cargo-marker/src/error.rs
- docs/book/src/usage/ci.md
- docs/book/src/usage/installation.md
- docs/book/src/usage/lint-crate-declaration.md
- docs/internal/release.md
- marker_api/README.md
- marker_lints/README.md
- marker_rustc_driver/README.md
- marker_rustc_driver/src/main.rs
- marker_uitest/README.md
- marker_utils/README.md
- rust-toolchain.toml
- scripts/release/install.ps1
- scripts/release/install.sh
- scripts/release/set-version.diff
- scripts/release/set-version.sh
- scripts/release/test.sh
- scripts/replace-in-regions.sh
- scripts/update-toolchain.sh
This is a prerequisite for https://github.com/rust-marker/marker/pull/281.
I updated the `set-version.sh` script to automatically use the rust toolchain version specified in `rust-toolchain.toml` during the release process, and also made the `update-toolchain.sh` update the specific `dev` regions where the toolchain version is mentioned for the next dev cycle.
> Use region replacements for release/dev rust toolchain versions

- .github/workflows/gh-pages.yml
Right now doing a pre-release is a bit broken due to the problem with the toolchain update. I don't know if we even really need pre-releases and how soon, but I don't think anything prevents us from having the ability to do these.
This is a small fix for the book deployment which is just one of the things affected by pre-releases. It makes sense not to deploy the book during a pre-release because it will contain the docs for the new release and not for the stable one.
> Don't publish the book on pre-releases

- cargo-marker/src/backend/driver.rs
- cargo-marker/src/utils/utf8.rs
- marker_rustc_driver/src/conversion/marker/ast/item.rs
- marker_rustc_driver/src/conversion/marker/common.rs
- marker_rustc_driver/src/conversion/marker/sem/ty.rs
- marker_rustc_driver/src/main.rs
- rust-toolchain.toml
New nightly bump after the `update-toolchain.sh` script has been updated in rust-marker/marker#284
This one my break cargos build cache. A simple `cargo clean` will fix any potential errors :)
Closes: https://github.com/rust-marker/marker/issues/236
> Chore: Bump nightly -> `2023-08-24`

- docs/book/src/usage/ci.md
- scripts/release/set-version.diff
- scripts/release/set-version.sh
- scripts/replace-in-regions.sh
I guess it may be a candidate for backporting to 0.3 book deployment :sweat:. At least the markdown text fix (not the script change)
> Fix the marker action version referenced in the book

- marker_rustc_driver/Cargo.toml
- marker_rustc_driver/src/bin/marker_rustc_driver.rs
- marker_rustc_driver/src/lib.rs
- marker_rustc_driver/src/lint_pass.rs
- marker_rustc_driver/src/main.rs
Fixes #257
How do you feel about this?
I would summarize the changes as follows:
- marker_rustc_driver/src/bin/marker_rustc_driver.rs is a new file that contains a slightly modified version of the old `main` function.
- `try_main` was updated to accept an `impl Iterator<Item = String>`. `main` passes `std::env::args()` as this argument.[^1^]
- The following were made `pub`:
- `try_main`
- `lint_pass`
- `MainError`
- `process_crate`
---
[^1^]: This change was not strictly necessary. But since `try_main` is now a public function, the idea of it reading from `std::env::args()` directly seemed weird to me.
> Rustc: Librarify `marker_rustc_driver`

- .github/workflows/release-on-tag.yml
- .github/workflows/release.yml
- scripts/release/upload.sh
The layout of `marker_rustc_driver-aarch64-unknown-linux-gnu.tar.gz` and `zip` turns out to differ from the layout of all other artifacts. This is because this version of driver is compiled separately using a custom quemu setup, packaging and upload and so it went slightly wrong.
The difference is that the file inside of the archive contains the architecture suffix, but it shouldn't.
I've manually updated the current 0.3.0 release by downloading the marker_rustc_driver ARM build, decompressing it, renaming the file to `marker_rustc_driver`, and running the part of `upload.sh` script that does the packaging.
> Fix archive layout for marker_rustc_driver on ARM

- .github/workflows/ci.yml
- marker_rustc_driver/src/conversion/marker/ast/expr.rs
Turns out a simple `cargo test` doesn't run doctests for binaries. It does run them for libraries though.
The solution is to separate the test command into two `cargo test --all-targets` (which, unintuitively, doesn't invoke doc tests https://github.com/rust-lang/cargo/issues/6669), and then run `cargo test --doc`.
This doesn't solve https://github.com/rust-marker/marker/issues/303 though.
> Run doc tests for binaries on CI

- .github/workflows/ci.yml
- docs/book/src/usage/ci.md
- scripts/download/lib.sh
- scripts/release/install.ps1
- scripts/release/install.sh
- scripts/release/qemu-setup.sh
- scripts/release/set-version.diff
Today on our CI the installation of marker randomly failed:
GitHub returned 403 due to some internal bugs I suppose. To fix this I added `--retry-all-errors` which should retry in such cases and added more configurations for retries. This way on CI we use the retry config that gives up in 30 minutes. This solves the problem of red master CI when doing a release (part of #274).
> Improve retries in the installation scripts

- CHANGELOG.md
- README.md
- marker_api/src/ast/expr.rs
- marker_api/src/ast/item.rs
- marker_api/src/ffi.rs
- marker_api/src/lib.rs
- marker_api/src/sem.rs
- marker_api/src/sem/item.rs
- marker_api/src/test.rs
- marker_lints/src/not_using_has_span_trait.rs
- marker_rustc_driver/src/conversion/marker.rs
- marker_rustc_driver/src/conversion/marker/ast/item.rs
- marker_rustc_driver/src/conversion/marker/sem.rs
- marker_rustc_driver/src/conversion/marker/sem/item.rs
- marker_uilints/src/lib.rs
- marker_uilints/tests/ui/context/test_ast_map.stderr
- marker_uilints/tests/ui/item/print_async_fn.stderr
- marker_uilints/tests/ui/item/print_fn_item.stderr
- marker_uilints/tests/ui/item/print_me_root_module.stderr
- marker_uilints/tests/ui/item/test_visibility.rs
- marker_uilints/tests/ui/item/test_visibility.stderr
- marker_uilints/tests/ui/print_adt_item.stderr
- marker_uilints/tests/ui/print_const_generics.stderr
- marker_uilints/tests/ui/print_use.stderr
Designing a sensible `Visibility` representation is surprisingly hard. I had to update the function names several times, and still feel like they can be improved. There is also still one util function missing, which requires the implementation of https://github.com/rust-marker/marker/issues/242 first. I've left a corresponding comment in the PR.
I think this implementation will cover 99% of the current use cases. This PR also updates the `not_using_has_span_trait` lint and enables it by default inside the `marker_api` crate
---
Closes: rust-marker/marker#26
> API: Make item `Visibility` visible in the API

- .github/workflows/ci.yml
- CHANGELOG.md
- marker_api/src/ast/expr/call_exprs.rs
- marker_api/src/ast/pat/or_pat.rs
- marker_api/src/ast/pat/ref_pat.rs
- marker_rustc_driver/src/conversion/marker/ast/expr.rs
- marker_rustc_driver/src/conversion/marker/ast/pat.rs
- marker_uilints/tests/ui/expr/print_await_expr.stderr
- marker_uilints/tests/ui/item/print_async_fn.stderr
- marker_uilints/tests/ui/print_assign_expr.stderr
- marker_uilints/tests/ui/print_cond_expr.stderr
- marker_uilints/tests/ui/print_ctor.stderr
- marker_uilints/tests/ui/print_path_expr.stderr
- marker_utils/src/visitor.rs
Some smaller breaking changes before `v0.4.0` probably best summarized by the changelog entry:
- Renamed `CallExpr::operand` to `CallExpr::func`
- Renamed `RefPat::pattern()` -> `RefPat::pat()`
- Renamed `OrPat::patterns()` -> `RefPat::pats()`
Yeah, and that's it :D
---
I also moved the semver check higher in our CI file. I thought about making it the first item, but I feel like the others are still more important and should be the first visible CI checks. Having semver higher up is already a nice change :)
---
Closes https://github.com/rust-marker/marker/issues/297
Closes https://github.com/rust-marker/marker/issues/295
> API: Rename `CallExpr::operand` -> `CallExpr::func`;  `*::pattern` -> `*::pat`

- scripts/release/qemu-setup.sh
The build failed in driver ARM build due to the usage of `--retry-all-errors`.
The build on master also failed, because we don't use this option on `ubuntu20.04`. I think we'll need to add a manual retry loop there as a crutch for old systems with old curl.
As for now I'll move the `v0`, `v0.4` and `v0.4.0` tags manually to this new commit in a `hotfix/0.4` branch and this will trigger the "release-on-tag" workflow again and it should update the GH release :crossed_fingers:
> Fix qemu setup using too new curl options

- cargo-marker/src/backend/driver.rs
- marker_api/src/ast/generic.rs
- marker_rustc_driver/src/conversion/marker/ast/expr.rs
- marker_rustc_driver/src/conversion/marker/ast/item.rs
- marker_rustc_driver/src/conversion/marker/sem/ty.rs
- marker_rustc_driver/src/conversion/rustc/unstable.rs
- marker_rustc_driver/src/lib.rs
- rust-toolchain.toml
Closes: https://github.com/rust-marker/marker/issues/280
> Chore: Bump nightly -> 2023-11-16

- .github/workflows/release-on-tag.yml
When last time I fixed the build of marker_rustc_driver on ARM I tested my changes only locally in an isolated folder where I manually "unit-tested" the `upload.sh` script. Of course, when the build happens on CI the folders layout is entirely different. That's why the ARM packaging script broke but in other way.
On CI we mount the `.` fodler as `/artifacts` in `quemu`, but `.` folder includes the `marker_rustc_driver` crate source code folder. So when we do `cp target/release/marker_rustc_driver /artifacts/marker_rustc_driver` we copy the binary inside of that folder...
I fixed this by mounting `./artifacts` which is guaranteed to be an empty folder.
Also manually fixed and reuploaded the artifacts in 0.4:
This time I tested it end-to-end in my fork repo
> Fix marker_rustc_driver build ARM just one more time

- CHANGELOG.md
- cargo-marker/src/backend/driver.rs
Closes https://github.com/rust-marker/marker/issues/318
I immediately identified the problem by the [logs](https://github.com/rust-marker/marker/issues/318#issuecomment-1825917130) because this bug is specific to Windows only.
It was described as "Problem 2" in the description of the PR https://github.com/rust-marker/marker/pull/217, although that appeared in a bit different place at that moment.
This is just a quick fix, it doesn't setup testing on CI. I just reproduced the problem manually on my windows laptop and fixed it.
> Cargo: Fix compiling driver from sources outside of the marker repo on Windows

- .github/workflows/ci.yml
- .github/workflows/release-on-tag.yml
- CHANGELOG.md
- Cargo.toml
- cargo-marker/src/backend/driver.rs
Fixes marker_rustc_driver crashing on windows with `exit code: 0xc0000005, STATUS_ACCESS_VIOLATION`. Reported in  https://github.com/rust-marker/marker/issues/318#issuecomment-1826098814.
I disabled LTO, in release build and it fixes the problem.
I extended the CI to perform a really simple release smoke test both for the current release and for the previous release (in github action test CI job).
Here, for example, you may see that the bug reproduces in master on the changed CI
- [CI job for the current version of marker](https://github.com/rust-marker/marker/actions/runs/6985541482/job/19009920759?pr=320#step:4:93)
- [CI job for the released version of marker](https://github.com/rust-marker/marker/actions/runs/6985541482/job/19009920759?pr=320#step:4:93)
With the disabled LTO …
> Disable buggy LTO

- .github/workflows/release-on-tag.yml
- scripts/download/cargo-release.sh
I was confused by [this warning on CI](https://github.com/rust-marker/marker/actions/runs/6984551469/job/19007537021#step:6:14)
It looked to me as if cargo release wanted to do a commit and push changes to the remote. I still don't understand why that warning is emitted because `cargo release` is used only for publishing. Maybe that's a micro-bug in `cargo-release`. Anyway, this time it was me who broke crates publishing. Hopefully, this was the last obstacle
> Remove params that aren't supported by `cargo release publish`

- CHANGELOG.md
- marker_api/src/common/id.rs
- marker_api/src/sem/ty.rs
- marker_api/src/sem/ty/fn_ty.rs
- marker_api/src/sem/ty/other_ty.rs
- marker_api/src/sem/ty/prim_ty.rs
- marker_api/src/sem/ty/ptr_ty.rs
- marker_api/src/sem/ty/sequence_ty.rs
- marker_api/src/sem/ty/trait_ty.rs
- marker_api/src/sem/ty/user_ty.rs
- marker_rustc_driver/src/conversion/marker/common.rs
- marker_rustc_driver/src/conversion/marker/sem/ty.rs
- marker_rustc_driver/src/conversion/rustc/common.rs
- marker_uilints/tests/ui/print_const_generics.stderr
- marker_uilints/tests/ui/print_semantic_ty.stderr
This PR adds boilerplate code required for the implementation of https://github.com/rust-marker/marker/issues/141. I've also changed all semantic type construction, to use the `TypedBuilder` instead of the old `new()` function.
This PR also includes some changes, visible to API consumers, probably best summarized by the changelog entires:
- `sem::TyKind` now implements `From<*>` for all semantic types.
- Renamed `sem::TyKind::FnTy` -> `sem::TyKind::Fn`
- Renamed `sem::TyKind::ClosureTy` -> `sem::TyKind::Closure`
That's basically it. Some boring repetitive code changes, which will hopefully make it easier to expand semantic types in the future :D
> API: Add impl `From<*>` for `sem::TyKind` and correct some names of semantic types

- marker_rustc_driver/src/lib.rs
If I'm honest, I still don't fully understand when and where the `--sysroot` argument is required. Clippy has very few comments on the topic. Miri has a few more, but also a custom setup in their `cargo-miri` interface, which is probably needed for the way miri operates.
Before https://github.com/rust-lang/rust/pull/103660, rustc used to use the path of the executable to get the system root, that's why Clippy and Miri had custom ways to search for the system root. When I wrote Marker's driver, I took Clippy's code for this part and refactored it for readability.
The referenced PR changed rustc's default behavior to use the path of the rustc library, which should work for Clippy, Miri and Marker. Clippy and Miri still have some minimal code, to check for an environment value. This PR …
> Rustc: Simplify `--sysroot` code after `rust#103660`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cargo-marker/src/backend/driver.rs
- marker_rustc_driver/src/lib.rs
The first commit is the same as rust-marker/marker#325
> Rustc: Simplify `--sysroot` code after `rust#103660` and prepare `0.4.3-rc`

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- cargo-marker/src/error.rs
- docs/book/src/usage/ci.md
- docs/book/src/usage/installation.md
- docs/book/src/usage/lint-crate-declaration.md
- docs/internal/release.md
- marker_api/README.md
- marker_lints/README.md
- marker_uitest/README.md
- marker_utils/README.md
- scripts/release/install.ps1
- scripts/release/install.sh
The main bug fix has already landed on master in #325. This pulls the necessary version changes for the CI test to master.
I've tried cherry-picking the release commits, but they had too many conflicts. Manually updating all `0.4.2` -> `0.4.3` was the most reasonable solution.
> Release: Take important changes from `hotfix/0.4`

- docs/book/src/usage/lint-crate-declaration.md
- scripts/release/set-version.diff
Tiny doc PR.
I have a bigger PR coming up, but it still needs a bit of refinement. I hope to open it early next week.
> Book: Use `--lints` instead of `--lint`

- action.yml
It looks like this is the default way linting should be run.
Tested it in https://github.com/rust-marker/lint-crate-template/pull/9
> Action: Run cargo marker with `--all-targets --all-features [--locked]` in GitHub action

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Not much to say, just some prep for the next release.
> Chore: Update Deps and increase MSRV to 1.70
