linter_driver_rustc/src/main.rs

Closes #13 
See [this comment](https://github.com/rust-linting/rust-linting/issues/13#issuecomment-1135583927) for an explanation.
r? @DevinR528

Allow binary creation in rustc driver for build scripts

---

linter_api/src/ast/common.rs
linter_api/src/ast/item.rs
linter_api/src/ast/item/const_item.rs
linter_api/src/ast/item/extern_crate_item.rs
linter_api/src/ast/item/mod_item.rs
linter_api/src/ast/item/static_item.rs
linter_api/src/ast/item/use_decl_item.rs
linter_api/src/ast/ty.rs
linter_api/src/lib.rs
linter_driver_rustc/src/conversion/common.rs
linter_lints/src/lib.rs

Use correct getter names and more `#[repr(C)]`

---

linter_adapter/src/context.rs
linter_api/src/ast/common.rs
linter_api/src/ast/common/callable.rs
linter_api/src/ast/generic.rs
linter_api/src/ast/generic/param.rs
linter_api/src/ast/item/const_item.rs
linter_api/src/ast/item/fn_item.rs
linter_api/src/ast/item/static_item.rs
linter_api/src/ast/item/ty_alias_item.rs
linter_api/src/ast/ty.rs
linter_api/src/ast/ty/alias_ty.rs
linter_api/src/ast/ty/raw_ptr_ty.rs
linter_api/src/ast/ty/ref_ty.rs
linter_api/src/ast/ty/relative_ty.rs
linter_api/src/ast/ty/self_ty.rs
linter_api/src/context.rs
linter_api/src/ffi.rs
linter_driver_rustc/src/context.rs
linter_driver_rustc/src/context/storage.rs
linter_driver_rustc/src/conversion.rs
linter_driver_rustc/src/conversion/common.rs
linter_driver_rustc/src/conversion/common/ast_path.rs
linter_driver_rustc/src/conversion/common/id.rs
linter_driver_rustc/src/conversion/common/unstable.rs
linter_driver_rustc/src/conversion/generic.rs
linter_driver_rustc/src/conversion/item.rs
linter_driver_rustc/src/conversion/ty.rs
linter_lints/tests/ui/find_item.rs
linter_lints/tests/ui/print_ty.stderr

Not a long description, as I feel like nobody is reading these. If you do, please leave me a comment, and I'll go into more detail. I'd also be very happy!!!
Reviews are welcome, but I'll merge it without, if there has been no activity by the next step.
---
Closes #56
Closes #38

Add more syntactic types, update rustc impl and general clean up

---

.cargo/config.toml
.github/workflows/rust.yml
.github/workflows/rust_bors.yml
Cargo.lock
bors.toml
cargo-linter/Cargo.toml
cargo-linter/src/main.rs
linter_driver_rustc/Cargo.toml
linter_driver_rustc/build.rs
linter_driver_rustc/src/main.rs
linter_lints/tests/compile_test.rs
util/update-toolchain.sh

A small cleanup PR, not much to say, just a few nice changes, before I try to rework more things in `cargo-linter`
As always, happy about reviews, but I'll merge this, if there has been no progress by the next PR :)
---
Closes #61 and progress on #60

Minor cleanup in cargo-linter and stable CI

---

docs/internal/README.md
docs/internal/driver-info.md
docs/internal/type-guidelines.md

Not sure if that works here, but
r? @xFrednet

Fixup internal docs

---

.github/workflows/rust_bors.yml

bors: run tests when no `.rs` files were changed

---

README.md
marker_adapter/README.md
marker_api/README.md
marker_lints/README.md

README.md fixups

---

.github/workflows/rust.yml
.github/workflows/rust_bors.yml
cargo-marker/src/driver.rs
marker_driver_rustc/src/conversion/marker/ty.rs
marker_driver_rustc/src/main.rs
rust-toolchain
util/update-toolchain.sh

Bump nightly -> 2023-01-26

---

marker_driver_rustc/src/conversion/marker/expr.rs

This PR replaces the `todo!` in `marker_driver_rustc` with a `eprintln!` and converts the `Expr` to an `Unstable` expression with most of the information stripped out.
It's not the best solution, but it will work for now.
Fixes `cargo dogfood` :)

fix panic in marker_driver_rustc

---

CODE_OF_CONDUCT.md

Here is my contribution to make the project shiny and approachable. Thank you for looking out for this!
r? @Niki4tap

Add Code of Conduct :)

---

marker_api/src/ast/expr.rs
marker_api/src/ast/expr/place_expr.rs
marker_driver_rustc/src/conversion/marker/expr.rs
marker_lints/tests/ui/print_place_expr.rs
marker_lints/tests/ui/print_place_expr.stdout

A simple PR to add two common expressions to the API.
Not much more to say. To everyone reading this, have a lovely day! :)
---
r? @Niki4tap If you don't mind :)
CC: #52

Add `IndexExpr` and `FieldExpr`

---

marker_api/src/ast/expr.rs
marker_api/src/ast/expr/op_exprs.rs
marker_driver_rustc/src/conversion/marker/expr.rs
marker_lints/tests/ui/print_op.rs
marker_lints/tests/ui/print_op.stdout

I noticed that I forgot to add a backend for operation expressions... until now :)
---
r? @Niki4tap if you have the time
cc: #52

Rustc backend for operations

---

.github/workflows/rust.yml
.github/workflows/rust_bors.yml
Cargo.toml
cargo-marker/src/driver.rs
marker_driver_rustc/src/context.rs
marker_driver_rustc/src/conversion/marker/expr.rs
marker_driver_rustc/src/main.rs
rust-toolchain
util/update-toolchain.sh

Just a simple nightly bump, not much more. Luckily, another simple one :)
---
Closes https://github.com/rust-marker/marker/issues/128
r? @ghost

bump nightly -> 2023-06-01

---

Cargo.lock
cargo-marker/Cargo.toml
cargo-marker/src/config.rs
marker_adapter/Cargo.toml
marker_rustc_driver/Cargo.toml

Just some regular maintenance, nothing too interesting :)
There are still some older dependencies in the tree. I'm guessing from `cargo_fetch`? I've created https://github.com/Niki4tap/cargo_fetch/issues/1 to ask about the status of that project :)

Maintanance: Update dependencies (where possible)

---

README.md
cargo-marker/README.md
res/marker-logo-rect.svg
res/marker-logo-round.svg
res/marker-logo.svg

What is Marker? Well, this! This repo! This project! This idea! Still not clear, well understandable. That's what README's are for. Allow me to introduce you to Marker's new business card. The first thing people will find when they stumble upon this project!
Okay, this makes the change sound more significant than it actually is. ^^ Anyways, I hope that this new README, gives a good first impression and defines what Marker actually is.
[:framed_picture: Rendered :framed_picture: ](https://github.com/xFrednet/marker/blob/151-this-is-readme/README.md)
---
A small but super important step for #151
Any feedback is very welcome!

Documentation: Update Marker's main README

---

.github/workflows/rust.yml

Woops, looks like I forgot to switch this back :sweat_smile:

CI: Switch CI to use ubuntu again

---

cargo-marker/src/backend/driver.rs
marker_rustc_driver/build.rs

Just a small update, to prevent the accidental installation of rustc's driver :)

Rustc: Warn when a user attempts to manually install the driver

---

README.md
cargo-marker/README.md
marker_adapter/Cargo.toml
marker_adapter/README.md
marker_api/README.md
marker_lints/Cargo.toml
marker_lints/README.md
marker_lints/src/lib.rs
marker_rustc_driver/Cargo.toml
marker_rustc_driver/README.md
marker_uilints/Cargo.toml
marker_uitest/README.md
marker_utils/Cargo.toml
marker_utils/README.md
util/update-toolchain.sh

What a day. This should cover markers documentation for now
Closes: https://github.com/rust-marker/marker/issues/151

Doc: Update adapter readme

---

Cargo.lock
README.md
cargo-marker/Cargo.toml
cargo-marker/README.md
cargo-marker/src/backend/driver.rs
cargo-marker/src/backend/toolchain.rs
cargo-marker/src/exit.rs
marker_adapter/Cargo.toml
marker_adapter/README.md
marker_api/Cargo.toml
marker_api/README.md
marker_lints/Cargo.toml
marker_lints/README.md
marker_rustc_driver/Cargo.toml
marker_rustc_driver/README.md
marker_rustc_driver/src/conversion.rs
marker_uilints/Cargo.toml
marker_uitest/Cargo.toml
marker_uitest/README.md
marker_uitest/src/lib.rs
marker_utils/Cargo.toml
marker_utils/README.md
rust-toolchain

This was a journey! I'll make a proper announcement, once this is merged :)

Release v0.1.1 :tada: 

---

.github/workflows/docs.yml
.github/workflows/gh-pages.yml
.github/workflows/rust_bors.yml
README.md
cargo-marker/README.md
docs/README.md
docs/book/book.toml
docs/book/src/SUMMARY.md
docs/book/src/usage/installation.md
docs/book/src/usage/lint-crate-declaration.md
docs/book/src/usage/lint-crate-security.md
scripts/download/mdbook.sh

Slow and steady wins the race, this is a tiny step in the journey of documenting Marker's usage, lint crate creating and development :)
Hopefully, an informative and maybe fun read :)

Book: Add new sections about installation and lint crate security

---

CONTRIBUTING.md
Cargo.lock
Cargo.toml
README.md
cargo-marker/README.md
cargo-marker/src/backend/driver.rs
cargo-marker/src/exit.rs
docs/book/src/usage/lint-crate-declaration.md
marker_lints/README.md
marker_utils/README.md

I've also ran `cargo update` to update all deps, where possible :)

Release: v0.2.0

---

.github/ISSUE_TEMPLATE/blank_issue.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/panic.yml
cargo-marker/src/cli.rs

I have tested these a bit in a private repo, and they seem to be working well. I've checked that with a spellchecker, but it's likely that there is still a typo somewhere. I'd highly appreciate it if anyone could double-check the templates.
Besides that, a small message for anyone who is reading this: Have a beautiful day, and thank you for checking in on Marker :heart:

Chore: Add magnificent new issue templates

---

marker_uitest/src/lib.rs

The `ui_test` setup from rust-marker/marker#263 broke another small thing. The `ui_test` folder was no longer being created, which caused the test to fail after the project has been cleaned. In Marker this wasn't noticeable, since we set a custom target directory, which was always created by cargo.
I've tested this fix with a local lint crate. Let's hope that's the last bug that slipped through :sweat_smile:

uitest: Use `CARGO_TARGET_DIR` as default and auto create required folders
